import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import "@liveblocks/react-ui/styles.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";

const OutfitFONT = Outfit({
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider>
            <html lang="en">
                <body className={`${OutfitFONT.className} antialiased`}>
                    <Toaster position="top-center" />
                    {children}
                </body>
            </html>
        </ClerkProvider>
    );
}
